kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-starter
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get" ]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelines"]
  verbs: ["get"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineresources"]
  verbs: ["list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create", "get", "list","watch"]
- apiGroups: ["tekton.dev"]
  resources: ["taskruns"]
  verbs: ["get"]
