apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-starter
  namespace: remote-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-starter
subjects:
- kind: ServiceAccount
  name: pipeline-starter
  namespace: remote-pipeline
