apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prod-pipeline
  namespace: prod-env
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  tasks:
  - name: remote
    taskRef:
      kind: Task
      name: remote
  - name: fetch-repository
    params:
      - name: url
        value: $(params.git-url)
      - name: deleteExisting
        value: 'true'
      - name: revision
        value: $(params.git-revision)
    runAfter: remote
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: shared-workspace
  - name: build-image
    params:
      - name: IMAGE
        value: $(params.IMAGE)
    runAfter:
      - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: dev-apply-manifests
    params:
      - name: project-name
        value: dev-env
    runAfter:
      - build-image
    taskRef:
      kind: Task
      name: apply-manifests
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: update-deployment-dev
    params:
      - name: deployment
        value: $(params.deployment-name)
      - name: IMAGE
        value: $(params.IMAGE)
      - name: project-name
        value: dev-env
    runAfter:
      - dev-apply-manifests
    taskRef:
      kind: Task
      name: update-deployment
  - name: test-task
    params:
      - name: APP_NAME
        value: $(params.deployment-name)
      - name: APP_VERSION
        value: '1.0'
      - name: DEPLOY_PROJECT
        value: dev-env
    runAfter:
      - update-deployment-dev
    taskRef:
      kind: Task
      name: test-app
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: promote-stage
    params:
      - name: project-name
        value: stage-env
    runAfter:
      - test-task
    taskRef:
      kind: Task
      name: apply-manifests
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: update-deployment-stage
    params:
      - name: deployment
        value: $(params.deployment-name)
      - name: IMAGE
        value: $(params.IMAGE)
      - name: project-name
        value: stage-env
    runAfter:
      - promote-stage
    taskRef:
      kind: Task
      name: update-deployment
