apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-app
spec:
  inputs:
    params:
      - name: APP_NAME
        description: The name of the application
        default: 'react-ui'
        type: string
      - name: APP_VERSION
        description: The version of the application
        default: '1.0'
        type: string
      - name: DEPLOY_PROJECT
        description: The project where you deploy the app
        default: 'dev-env'
        type: string  

  steps:
      - name: test-app
        image: quay.io/openshift/origin-cli:latest
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get deployment $(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)
  workspaces:
    - name: source
